// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("redmetrics")
	ScopeName = "github.com/CloudDetail/apo-otel-collector/pkg/connector/redmetricsconnector"
)

const (
	TracesToMetricsStability = component.StabilityLevelAlpha
)
