// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("skywalking")
	ScopeName = "github.com/CloudDetail/apo-otel-collector/pkg/receiver/skywalkingreceiver"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelBeta
)
