// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/CloudDetail/apo-otel-collector

go 1.21.0

toolchain go1.21.5

require (
	github.com/CloudDetail/apo-otel-collector/pkg/connector/redmetricsconnector v0.0.0
	github.com/CloudDetail/apo-otel-collector/pkg/extension/fillprocextension v0.0.0
	github.com/CloudDetail/apo-otel-collector/pkg/processor/backsamplingprocessor v0.0.0
	github.com/CloudDetail/apo-otel-collector/pkg/processor/metadataprocessor v0.0.0
	github.com/CloudDetail/apo-otel-collector/pkg/receiver/otlpreceiver v0.0.0
	github.com/CloudDetail/apo-otel-collector/pkg/receiver/prometheusremotewritereceiver v0.0.0
	github.com/CloudDetail/apo-otel-collector/pkg/receiver/skywalkingreceiver v0.0.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/clickhouseexporter v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/k8seventsreceiver v0.103.0
	github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.103.0
	go.opentelemetry.io/collector/confmap/converter/expandconverter v0.103.0
	go.opentelemetry.io/collector/confmap/provider/envprovider v0.103.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v0.103.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v0.103.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v0.103.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v0.103.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.103.0
	go.opentelemetry.io/collector/exporter/loggingexporter v0.103.0
	go.opentelemetry.io/collector/exporter/nopexporter v0.103.0
	go.opentelemetry.io/collector/exporter/otlpexporter v0.103.0
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.103.0
	go.opentelemetry.io/collector/otelcol v0.103.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.103.0
	go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.103.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)

replace github.com/CloudDetail/apo-otel-collector/pkg/common => ./pkg/common

replace github.com/CloudDetail/apo-otel-collector/pkg/fillproc => ./pkg/fillproc

replace github.com/CloudDetail/apo-otel-collector/pkg/sqlprune => ./pkg/sqlprune

replace github.com/CloudDetail/apo-otel-collector/pkg/connector/redmetricsconnector => ./pkg/connector/redmetricsconnector

replace github.com/CloudDetail/apo-otel-collector/pkg/extension/fillprocextension => ./pkg/extension/fillprocextension

replace github.com/CloudDetail/apo-otel-collector/pkg/processor/backsamplingprocessor => ./pkg/processor/backsamplingprocessor

replace github.com/CloudDetail/apo-otel-collector/pkg/processor/metadataprocessor => ./pkg/processor/metadataprocessor

replace github.com/CloudDetail/apo-otel-collector/pkg/receiver/otlpreceiver => ./pkg/receiver/otlpreceiver

replace github.com/CloudDetail/apo-otel-collector/pkg/receiver/skywalkingreceiver => ./pkg/receiver/skywalkingreceiver

replace github.com/CloudDetail/apo-otel-collector/pkg/receiver/prometheusremotewritereceiver => ./pkg/receiver/prometheusremotewritereceiver
