extensions:
  fill_proc:
    enable: true
    interval: 5s
  pprof:
    endpoint: 0.0.0.0:1777
receivers:
  otlp:
    fillproc_extension: fill_proc
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 999999999
      http:
        endpoint: 0.0.0.0:4318
  skywalking:
    fillproc_extension: fill_proc
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800
      http:
        endpoint: 0.0.0.0:12800
  prometheus/own_metrics:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:1778']
connectors:
  redmetrics:
    server_enabled: true
    db_enabled: true
    external_enabled: true
    mq_enabled: true
    client_entry_url_enabled: true
    cache_entry_url_time: 30s
    unmatch_url_expire_time: 60s
    dimensions_cache_size: 1000
    max_services_to_track: 256
    max_operations_to_track_per_service: 2048
    metrics_flush_interval: 15s
    # vm(VictoriaMetrics) or prom(Promethues)
    metrics_type: "vm"
    # latency_histogram_buckets: [5ms, 10ms, 20ms, 30ms, 50ms, 80ms, 100ms, 150ms, 200ms, 300ms, 400ms, 500ms, 800ms, 1200ms, 3s, 5s, 10s, 15s, 20s, 30s, 40s, 50s, 60s]
    # httpMethod / topUrl
    http_parser: topUrl
processors:
  batch:
    send_batch_size: 10000
    timeout: 2s
  backsampling:
    # Notify EbpfAgent Collect OnOffMetric and Profile. It will be disabled when set to zero.
    ebpf_port: 0
    adaptive:
      enable: false
      span_slow_threshold: 10s
      service_sample_window: 1s
      service_sample_count: 1
      memory_check_interval: 2s
      memory_limit_mib_threshold: 200
      traceid_holdtime: 60s
    sampler:
      log_enable: true
      normal_top_sample: false
      normal_sample_wait_time: 60
      open_slow_sampling: true
      open_error_sampling: true
      enable_tail_base_profiling: true
      sample_trace_repeat_num: 3
      sample_trace_wait_time: 30
      sample_trace_ignore_threshold: 0
      sample_trace_slow_threshold_ms: 100
      silent_period: 5
      silent_count: 1
      silent_mode: window
    controller:
      host: 10.0.2.4
      port: 19090
      interval_query_slow_threshold: 30
      interval_query_sample: 2
      interval_send_trace: 1
    notify:
      enabled: false
exporters:
  nop:
  debug:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200
  otlp:
    endpoint: "http://localhost:4317"
    tls:
      insecure: true
  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    endpoint: http://localhost:8428/opentelemetry
service:
  telemetry:
    logs:
      level: info
    metrics:
      level: basic
      address: ":1778"
  extensions: [pprof, fill_proc]
  pipelines:
    traces/red:
      receivers: [otlp, skywalking]
      processors: [batch]
      exporters: [redmetrics]
    traces:
      receivers: [otlp, skywalking]
      processors: [backsampling, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, redmetrics]
      processors: []
      exporters: [otlphttp/victoriametrics]
    metrics/sw:
      receivers: [skywalking]
      processors: []
      exporters: [nop]
    metrics/own_metrics:
      receivers: [prometheus/own_metrics]
      exporters: [otlphttp/victoriametrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
