receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 999999999
      http:
        endpoint: 0.0.0.0:4318
  k8s_events:
    auth_type: serviceAccount
    namespaces: [all]
  skywalking:
    protocols:
      grpc:
        endpoint: 0.0.0.0:11800 # 接收 SkyWalking Agent 上报的 Trace 数据
      http:
        endpoint: 0.0.0.0:12800 # 接收从前端/ nginx 等 HTTP 协议上报的 Trace 数据
processors:
  batch:
    send_batch_size: 10000
    timeout: 2s
  metadata:
    # 需要填充K8s信息的指标前缀
    metric_prefix: "kindling_"
    # k8s数据源
    kube_source:
      # kube_auth_type, support serviceAccount and kubeConfig, default is serviceAccount
      kube_auth_type: serviceAccount
      # kube_auth_config, kubeConfig file path, only used when kube_auth_type is kubeConfig
      kube_auth_config: ~/.kube/config
      # cluster_id, setup cluster id in kube metadata
      cluster_id: ""
    exporter:
      # remote_write_addr, push kube metadata to other server, remove if not need
      remote_write_addr: apo-backend-svc:8080/metadata
      # fetch_server_port, allowed other client fetch from this port, remove if not need
      fetch_server_port: 8080
connectors:
  redmetrics:
    # 开启服务端RED指标生成
    server_enabled: true
    # 开启DB RED指标生成
    db_enabled: true
    # 开启HTTP/RPC对外调用 RED指标生成
    external_enabled: true
    # 开启MQ RED指标生成
    mq_enabled: true
    # 开启对外调用添加入口URL
    client_entry_url_enabled: false
    # 未匹配的ExitSpan缓存时间
    unmatch_url_expire_time: 60s
    # RED Key缓存的数量，超过则清理；用于清理已失效PID数据.
    dimensions_cache_size: 1000
    # 指标发送间隔
    metrics_flush_interval: 60s
    # 最大监控服务数，超过则将服务名打标为 overflow_service.
    max_services_to_track: 256
    # 每个服务下最大URL数，超过则将URL打标为 overflow_operation.
    max_operations_to_track_per_service: 2048
    # vm(VictoriaMetrics) or prom(Promethues)
    metrics_type: "vm"
    # Promethues场景下需指定分桶.
    latency_histogram_buckets: [5ms, 10ms, 20ms, 30ms, 50ms, 80ms, 100ms, 150ms, 200ms, 300ms, 400ms, 500ms, 800ms, 1200ms, 3s, 5s, 10s, 15s, 20s, 30s, 40s, 50s, 60s]
    # URL收敛算法：httpMethod / topUrl
    http_parser: topUrl
exporters:
  nop:
  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200
  otlp:
    endpoint: http://apo-jaeger-collector-nodeport-svc:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: localhost:4317
  prometheus:
    endpoint: localhost:9500
  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    endpoint: http://apo-victoria-metrics-single-server-svc:8428/opentelemetry
    tls:
      insecure: true
  clickhouse/logs:
    endpoint: tcp://apo-clickhouse:9000?dial_timeout=10s&compress=lz4
    username: admin
    password: Apo@123456
    database: apo
    ttl: 72h
    create_schema: true
    logs_table_name: ilogtail_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  clickhouse/k8sevent:
    endpoint: tcp://apo-clickhouse:9000?dial_timeout=10s&compress=lz4
    username: admin
    password: Apo@123456
    database: apo
    ttl: 720h
    create_schema: true
    logs_table_name: k8s_events
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
      # cluster_name: my_cluster
      # table_engine:
      #   name: ReplicatedMergeTree
      #   params:
service:
  telemetry:
    logs:
      level: info
    metrics:
      level: none
  pipelines:
    traces:
      receivers: [otlp, skywalking]
      processors: [batch]
      exporters: [otlp]
    traces/red:
      receivers: [otlp]
      processors: [batch]
      exporters: [redmetrics]
    metrics:
      receivers: [otlp, redmetrics]
      processors: [batch, metadata]
      exporters: [otlphttp/victoriametrics]
    metrics/sw:
      receivers: [skywalking]
      processors: []
      exporters: [nop]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse/logs]
    logs/k8sevent:
      receivers: [k8s_events]
      processors: [batch]
      exporters: [clickhouse/k8sevent]
