// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bearertokenauth")
	ScopeName = "github.com/CloudDetail/apo-otel-collector/pkg/extension/tenantextension"
)

const (
	ExtensionStability = component.StabilityLevelBeta
)
