// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("fill_proc")
	ScopeName = "github.com/CloudDetail/apo-otel-collector/pkg/extension/fillprocextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
