// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("backsampling")
	ScopeName = "github.com/CloudDetail/apo-otel-collector/pkg/processor/backsamplingprocessor"
)

const (
	TracesStability = component.StabilityLevelBeta
)
