// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.3
// source: internal/model/apo_sample.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SampleMetric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryTime   int64  `protobuf:"varint,1,opt,name=queryTime,proto3" json:"queryTime,omitempty"`
	NodeIp      string `protobuf:"bytes,2,opt,name=nodeIp,proto3" json:"nodeIp,omitempty"`
	CacheSecond int64  `protobuf:"varint,3,opt,name=cacheSecond,proto3" json:"cacheSecond,omitempty"`
	Memory      uint64 `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	MemoryLimit uint64 `protobuf:"varint,5,opt,name=memoryLimit,proto3" json:"memoryLimit,omitempty"`
}

func (x *SampleMetric) Reset() {
	*x = SampleMetric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_apo_sample_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMetric) ProtoMessage() {}

func (x *SampleMetric) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_apo_sample_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMetric.ProtoReflect.Descriptor instead.
func (*SampleMetric) Descriptor() ([]byte, []int) {
	return file_internal_model_apo_sample_proto_rawDescGZIP(), []int{0}
}

func (x *SampleMetric) GetQueryTime() int64 {
	if x != nil {
		return x.QueryTime
	}
	return 0
}

func (x *SampleMetric) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *SampleMetric) GetCacheSecond() int64 {
	if x != nil {
		return x.CacheSecond
	}
	return 0
}

func (x *SampleMetric) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *SampleMetric) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

type SampleResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SampleResult) Reset() {
	*x = SampleResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_apo_sample_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleResult) ProtoMessage() {}

func (x *SampleResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_apo_sample_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleResult.ProtoReflect.Descriptor instead.
func (*SampleResult) Descriptor() ([]byte, []int) {
	return file_internal_model_apo_sample_proto_rawDescGZIP(), []int{1}
}

func (x *SampleResult) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_internal_model_apo_sample_proto protoreflect.FileDescriptor

var file_internal_model_apo_sample_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x61, 0x70, 0x6f, 0x5f, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x22, 0xa0, 0x01, 0x0a, 0x0c,
	0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x24,
	0x0a, 0x0c, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0x51, 0x0a, 0x0d, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69,
	0x6e, 0x67, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x1a,
	0x16, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x53, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_model_apo_sample_proto_rawDescOnce sync.Once
	file_internal_model_apo_sample_proto_rawDescData = file_internal_model_apo_sample_proto_rawDesc
)

func file_internal_model_apo_sample_proto_rawDescGZIP() []byte {
	file_internal_model_apo_sample_proto_rawDescOnce.Do(func() {
		file_internal_model_apo_sample_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_model_apo_sample_proto_rawDescData)
	})
	return file_internal_model_apo_sample_proto_rawDescData
}

var file_internal_model_apo_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_model_apo_sample_proto_goTypes = []interface{}{
	(*SampleMetric)(nil), // 0: kindling.SampleMetric
	(*SampleResult)(nil), // 1: kindling.SampleResult
}
var file_internal_model_apo_sample_proto_depIdxs = []int32{
	0, // 0: kindling.SampleService.GetSampleValue:input_type -> kindling.SampleMetric
	1, // 1: kindling.SampleService.GetSampleValue:output_type -> kindling.SampleResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_model_apo_sample_proto_init() }
func file_internal_model_apo_sample_proto_init() {
	if File_internal_model_apo_sample_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_model_apo_sample_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleMetric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_model_apo_sample_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_model_apo_sample_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_model_apo_sample_proto_goTypes,
		DependencyIndexes: file_internal_model_apo_sample_proto_depIdxs,
		MessageInfos:      file_internal_model_apo_sample_proto_msgTypes,
	}.Build()
	File_internal_model_apo_sample_proto = out.File
	file_internal_model_apo_sample_proto_rawDesc = nil
	file_internal_model_apo_sample_proto_goTypes = nil
	file_internal_model_apo_sample_proto_depIdxs = nil
}
