// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.3
// source: internal/model/apo_slowthreshold.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlowThresholdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *SlowThresholdRequest) Reset() {
	*x = SlowThresholdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowThresholdRequest) ProtoMessage() {}

func (x *SlowThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowThresholdRequest.ProtoReflect.Descriptor instead.
func (*SlowThresholdRequest) Descriptor() ([]byte, []int) {
	return file_internal_model_apo_slowthreshold_proto_rawDescGZIP(), []int{0}
}

func (x *SlowThresholdRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type SlowThresholdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datas      []*SlowThresholdData   `protobuf:"bytes,1,rep,name=datas,proto3" json:"datas,omitempty"`
	Exceptions []*ExceptionSwitchData `protobuf:"bytes,2,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
}

func (x *SlowThresholdResponse) Reset() {
	*x = SlowThresholdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowThresholdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowThresholdResponse) ProtoMessage() {}

func (x *SlowThresholdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowThresholdResponse.ProtoReflect.Descriptor instead.
func (*SlowThresholdResponse) Descriptor() ([]byte, []int) {
	return file_internal_model_apo_slowthreshold_proto_rawDescGZIP(), []int{1}
}

func (x *SlowThresholdResponse) GetDatas() []*SlowThresholdData {
	if x != nil {
		return x.Datas
	}
	return nil
}

func (x *SlowThresholdResponse) GetExceptions() []*ExceptionSwitchData {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

type SlowThresholdData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url         string  `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ContainerId string  `protobuf:"bytes,2,opt,name=containerId,proto3" json:"containerId,omitempty"`
	Value       float64 `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Type        string  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Range       string  `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	ServiceName string  `protobuf:"bytes,6,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Multiple    float64 `protobuf:"fixed64,7,opt,name=multiple,proto3" json:"multiple,omitempty"`
}

func (x *SlowThresholdData) Reset() {
	*x = SlowThresholdData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlowThresholdData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowThresholdData) ProtoMessage() {}

func (x *SlowThresholdData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowThresholdData.ProtoReflect.Descriptor instead.
func (*SlowThresholdData) Descriptor() ([]byte, []int) {
	return file_internal_model_apo_slowthreshold_proto_rawDescGZIP(), []int{2}
}

func (x *SlowThresholdData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SlowThresholdData) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SlowThresholdData) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SlowThresholdData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SlowThresholdData) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *SlowThresholdData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SlowThresholdData) GetMultiple() float64 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

type ExceptionSwitchData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Url         string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	MarkError   bool   `protobuf:"varint,3,opt,name=markError,proto3" json:"markError,omitempty"`
}

func (x *ExceptionSwitchData) Reset() {
	*x = ExceptionSwitchData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExceptionSwitchData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExceptionSwitchData) ProtoMessage() {}

func (x *ExceptionSwitchData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_apo_slowthreshold_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExceptionSwitchData.ProtoReflect.Descriptor instead.
func (*ExceptionSwitchData) Descriptor() ([]byte, []int) {
	return file_internal_model_apo_slowthreshold_proto_rawDescGZIP(), []int{3}
}

func (x *ExceptionSwitchData) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ExceptionSwitchData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExceptionSwitchData) GetMarkError() bool {
	if x != nil {
		return x.MarkError
	}
	return false
}

var File_internal_model_apo_slowthreshold_proto protoreflect.FileDescriptor

var file_internal_model_apo_slowthreshold_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2f, 0x61, 0x70, 0x6f, 0x5f, 0x73, 0x6c, 0x6f, 0x77, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f,
	0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69,
	0x6e, 0x67, 0x22, 0x26, 0x0a, 0x14, 0x53, 0x6c, 0x6f, 0x77, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68,
	0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x89, 0x01, 0x0a, 0x15, 0x53,
	0x6c, 0x6f, 0x77, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x53,
	0x6c, 0x6f, 0x77, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x12, 0x3d, 0x0a, 0x0a, 0x65, 0x78, 0x63, 0x65, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x69,
	0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a, 0x65, 0x78, 0x63, 0x65,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xc5, 0x01, 0x0a, 0x11, 0x53, 0x6c, 0x6f, 0x77, 0x54,
	0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x22, 0x67,
	0x0a, 0x13, 0x45, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x72,
	0x6b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6d, 0x61,
	0x72, 0x6b, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x6f, 0x0a, 0x14, 0x53, 0x6c, 0x6f, 0x77, 0x54,
	0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x57, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x6c, 0x6f, 0x77, 0x54, 0x68, 0x72, 0x65,
	0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x1e, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x53, 0x6c, 0x6f, 0x77, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6b, 0x69, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67,
	0x2e, 0x53, 0x6c, 0x6f, 0x77, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_model_apo_slowthreshold_proto_rawDescOnce sync.Once
	file_internal_model_apo_slowthreshold_proto_rawDescData = file_internal_model_apo_slowthreshold_proto_rawDesc
)

func file_internal_model_apo_slowthreshold_proto_rawDescGZIP() []byte {
	file_internal_model_apo_slowthreshold_proto_rawDescOnce.Do(func() {
		file_internal_model_apo_slowthreshold_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_model_apo_slowthreshold_proto_rawDescData)
	})
	return file_internal_model_apo_slowthreshold_proto_rawDescData
}

var file_internal_model_apo_slowthreshold_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_model_apo_slowthreshold_proto_goTypes = []interface{}{
	(*SlowThresholdRequest)(nil),  // 0: kindling.SlowThresholdRequest
	(*SlowThresholdResponse)(nil), // 1: kindling.SlowThresholdResponse
	(*SlowThresholdData)(nil),     // 2: kindling.SlowThresholdData
	(*ExceptionSwitchData)(nil),   // 3: kindling.ExceptionSwitchData
}
var file_internal_model_apo_slowthreshold_proto_depIdxs = []int32{
	2, // 0: kindling.SlowThresholdResponse.datas:type_name -> kindling.SlowThresholdData
	3, // 1: kindling.SlowThresholdResponse.exceptions:type_name -> kindling.ExceptionSwitchData
	0, // 2: kindling.SlowThresholdService.QuerySlowThreshold:input_type -> kindling.SlowThresholdRequest
	1, // 3: kindling.SlowThresholdService.QuerySlowThreshold:output_type -> kindling.SlowThresholdResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_model_apo_slowthreshold_proto_init() }
func file_internal_model_apo_slowthreshold_proto_init() {
	if File_internal_model_apo_slowthreshold_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_model_apo_slowthreshold_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlowThresholdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_model_apo_slowthreshold_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlowThresholdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_model_apo_slowthreshold_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlowThresholdData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_model_apo_slowthreshold_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExceptionSwitchData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_model_apo_slowthreshold_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_model_apo_slowthreshold_proto_goTypes,
		DependencyIndexes: file_internal_model_apo_slowthreshold_proto_depIdxs,
		MessageInfos:      file_internal_model_apo_slowthreshold_proto_msgTypes,
	}.Build()
	File_internal_model_apo_slowthreshold_proto = out.File
	file_internal_model_apo_slowthreshold_proto_rawDesc = nil
	file_internal_model_apo_slowthreshold_proto_goTypes = nil
	file_internal_model_apo_slowthreshold_proto_depIdxs = nil
}
