name: Build Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    
    - name: Install Tools
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; 
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  
    - name: Install Make
      run: choco install make
  
    - name: Get Git Tag
      run: |
        $tag = git describe --tags --always
        echo "APP_VERSION=$tag" >> $env:GITHUB_ENV
  
    - name: Build the executable
      run: make otelcol
  
    - name: Archive the executable
      run: |
        rename-Item otelcol -NewName otelcol.exe
        Compress-Archive -Path otelcol.exe -DestinationPath otelcol.zip

    - name: Upload to OSS
      env:
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_BUCKET: apo-oss
        OSS_ENDPOINT: https://oss-cn-hangzhou.aliyuncs.com/
      run: |
        Invoke-WebRequest -Uri "https://gosspublic.alicdn.com/ossutil/1.7.19/ossutil64.zip" -OutFile "ossutil64.zip"
        Expand-Archive -Path "ossutil64.zip" -DestinationPath "ossutil"
        .\ossutil\ossutil64.exe config -e $env:OSS_ENDPOINT -i $env:OSS_ACCESS_KEY_ID -k $env:OSS_ACCESS_KEY_SECRET -c C:\\Users\user\.ossutilconfig
        .\ossutil\ossutil64.exe cp otelcol.zip oss://$env:OSS_BUCKET/otelcol-windows-amd64-${{ env.APP_VERSION }}.zip
      